Repository oemof/oemof-thermal, pull requests merged in 2020-03, with the labels that each got.

#75 Add function tests for solar thermal collector
  examples/solar_thermal_collector/data/data_flat_collector.csv
  tests/test_functions.py
Labels: enhancement

#89 Features/docs overview text
  docs/getting_started.rst
  docs/index.rst
Labels: documentation, enhancement

#90 Replace 'oemof heat' by 'oemof.thermal' in conf.py
  docs/conf.py
  docs/getting_started.rst
Labels: documentation
