Repository oemof/oemof-thermal, pull requests merged in 2020-04, with the labels that each got.

#91 Add a .png to each .svg file in _pics
  docs/_pics/README.rst
  docs/_pics/compare_storage_models.png
  docs/_pics/emission_allocation_methods.png
  docs/_pics/stratified_thermal_storage.png
  docs/cogeneration.rst
  docs/stratified_thermal_storage.rst
Labels: documentation

#76 Features/improve docu pics
  docs/_pics/concentrating_solar_power.png
  docs/_pics/concentrating_solar_power.svg
  docs/_pics/scheme.png
  docs/_pics/solar_thermal_collector.svg
  docs/concentrating_solar_power.rst
  docs/whats_new/v0-0-2.rst
Labels: documentation

#43 Features/facades
  .travis.yml
  docs/api/oemof-thermal.rst
  docs/stratified_thermal_storage.rst
  examples/stratified_thermal_storage/plots.py
  examples/stratified_thermal_storage/stratified_thermal_storage.csv
  examples/stratified_thermal_storage/stratified_thermal_storage.py
  examples/stratified_thermal_storage/stratified_thermal_storage_facade.py
  examples/stratified_thermal_storage/stratified_thermal_storage_investment_option_1.py
  examples/stratified_thermal_storage/stratified_thermal_storage_investment_option_1_facade.py
  examples/stratified_thermal_storage/stratified_thermal_storage_investment_option_2.py
  examples/stratified_thermal_storage/stratified_thermal_storage_investment_option_2_facade.py
  src/oemof/thermal/facades.py
  src/oemof/thermal/stratified_thermal_storage.py
  tests/lp_files/stratified_thermal_storage.lp
  tests/lp_files/stratified_thermal_storage_invest_option_1.lp
  tests/lp_files/stratified_thermal_storage_invest_option_2.lp
  tests/test_constraints.py
  tests/test_functions.py
Labels: enhancement, feedback wanted

#98 Explain thermal storage facade in docs
  docs/_pics/stratified_thermal_storage.png
  docs/api.rst
  docs/getting_started.rst
  docs/stratified_thermal_storage.rst
  docs/whats_new/v0-0-2.rst
Labels: documentation

#77 Add csp facade
  docs/whats_new/v0-0-2.rst
  examples/concentrating_solar_power/csp_plant_example.py
  examples/concentrating_solar_power/example_csp_facade.py
  src/oemof/thermal/concentrating_solar_power.py
  src/oemof/thermal/facades.py
  tests/lp_files/csp_collector.lp
  tests/test_constraints.py
Labels: feedback wanted, help wanted

#107 Fixes/docstring thermal storage
  src/oemof/thermal/facades.py
Labels: documentation

#104 Add documentation of solar thermal collectors facades
  docs/solar_thermal_collector.rst
  src/oemof/thermal/solar_thermal_collector.py
Labels: documentation
