Repository oemof/oemof-thermal, pull requests merged in 2020-02, with the labels that each got.

#67 Add status badges to readme
  .travis.yml
  README.rst
Labels: documentation

#66 Solve bugs / inconsistencies in solar thermal collector documentation
  docs/solar_thermal_collector.rst
  src/oemof/thermal/solar_thermal_collector.py
Labels: documentation

#70 Correct default values in stratified_thermal_storage.py
  src/oemof/thermal/stratified_thermal_storage.py
Labels: bug

#38 Add tests for storage preprocessing functions
  tests/test_functions.py
Labels: enhancement

#42 Improvement of documentation of thermal storage
  docs/_pics/stratified_thermal_storage.svg
  docs/stratified_thermal_storage.rst
Labels: documentation

#72 Features/cogeneration
  docs/_pics/emission_allocation_methods.svg
  docs/api/oemof-thermal.rst
  docs/cogeneration.rst
  docs/index.rst
  examples/cogeneration/emission_allocation_methods.py
  src/oemof/thermal/cogeneration.py
  tests/test_functions.py
Labels: enhancement, feedback wanted
